name: echolang
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  whisper_ggml: ^1.7.0
  record: ^6.1.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  onnxruntime: ^1.4.1
  # sentencepiece_ffi: ^0.1.3
  onnx_translation: ^0.1.2
  ffi: ^2.1.5
  # flutter_sound: ^9.30.0
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/jfk.wav
    - assets/igbo_audio/

    - assets/models/
    - assets/models/onnx_model_ig_en/

    - assets/models/onnx_model_ig_en/encoder_model.onnx
    - assets/models/onnx_model_ig_en/decoder_model.onnx
    - assets/models/onnx_model_ig_en/vocab.json
    - assets/models/onnx_model_ig_en/tokenizer_config.json
    - assets/models/onnx_model_ig_en/generation_config.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
